version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      # Upgrade AWS CLI to the latest version; Install Leiningen; Install Clojure CLI tools
      - cd $HOME
      - pip install --upgrade awscli
      - wget https://raw.github.com/technomancy/leiningen/stable/bin/lein; chmod +x lein; mv lein /bin;
      - LEIN_ROOT=true lein
      - mkdir clj_tools_install; cd clj_tools_install
      - curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh; chmod +x linux-install-1.10.0.411.sh; ./linux-install-1.10.0.411.sh
      - cd $CODEBUILD_SRC_DIR

  pre_build:
    commands:
      - date

  build:
    commands:
      - LEIN_ROOT=true lein uberjar

artifacts:
  files:
    - target/*-standalone.jar
