---
template_path: GitMirror.yaml
parameters:
  VpcId: vpc-73ac1215
  SubnetId: subnet-85dee6ba
  JarBucket: sig-lambda-stage
  JarPath: git-mirror/git-mirror-13-pkg.jar
  PrivateKeyParam: delete-me-ellucian-git-private-key
  MirrorConfParam: delete-me-git-mirror-conf
