---
template_path: GitMirror.yaml
parameters:
  VpcId: vpc-73ac1215
  SubnetId: subnet-85dee6ba
  JarBucket: sig-lambda-stage
  JarPath: git-mirror/git-mirror-24-pkg.jar
  PrivateKeyParam: delete-me-ellucian-git-private-key
  MirrorConfParam: delete-me-git-mirror-conf
  CodeCommitCredsParam: delete-me-git-mirror-creds
  AlarmTopicArn: arn:aws:sns:us-east-1:803071473383:NotifyMe
